# bash venezuela_single_job_submit_general 1021 venezuela_configs/config_venezuela_COA1_buffer_5-sim-1021.json
# bash venezuela_single_job_submit_general 1022 venezuela_configs/config_venezuela_COA1_buffer_5-sim-1022.json
# bash venezuela_single_job_submit_general 1023 venezuela_configs/config_venezuela_COA1_buffer_5-sim-1023.json
# bash venezuela_single_job_submit_general 1024 venezuela_configs/config_venezuela_COA1_buffer_5-sim-1024.json
# bash venezuela_single_job_submit_general 1025 venezuela_configs/config_venezuela_COA1_buffer_5-sim-1025.json
# bash venezuela_single_job_submit_general 1026 venezuela_configs/config_venezuela_COA1_buffer_5-sim-1026.json
# bash venezuela_single_job_submit_general 1027 venezuela_configs/config_venezuela_COA1_buffer_5-sim-1027.json
# bash venezuela_single_job_submit_general 1028 venezuela_configs/config_venezuela_COA1_buffer_5-sim-1028.json

# bash venezuela_single_job_submit_general 1031 venezuela_configs/config_venezuela_COA2_buffer_5-sim-1031.json
# bash venezuela_single_job_submit_general 1032 venezuela_configs/config_venezuela_COA2_buffer_5-sim-1032.json
# bash venezuela_single_job_submit_general 1033 venezuela_configs/config_venezuela_COA2_buffer_5-sim-1033.json
# bash venezuela_single_job_submit_general 1034 venezuela_configs/config_venezuela_COA2_buffer_5-sim-1034.json
# bash venezuela_single_job_submit_general 1035 venezuela_configs/config_venezuela_COA2_buffer_5-sim-1035.json
# bash venezuela_single_job_submit_general 1036 venezuela_configs/config_venezuela_COA2_buffer_5-sim-1036.json
# bash venezuela_single_job_submit_general 1037 venezuela_configs/config_venezuela_COA2_buffer_5-sim-1037.json
# bash venezuela_single_job_submit_general 1038 venezuela_configs/config_venezuela_COA2_buffer_5-sim-1038.json

# bash venezuela_single_job_submit_general 1041 venezuela_configs/config_venezuela_COA3_buffer_5-sim-1041.json
# bash venezuela_single_job_submit_general 1042 venezuela_configs/config_venezuela_COA3_buffer_5-sim-1042.json
# bash venezuela_single_job_submit_general 1043 venezuela_configs/config_venezuela_COA3_buffer_5-sim-1043.json
# bash venezuela_single_job_submit_general 1044 venezuela_configs/config_venezuela_COA3_buffer_5-sim-1044.json
# bash venezuela_single_job_submit_general 1045 venezuela_configs/config_venezuela_COA3_buffer_5-sim-1045.json
# bash venezuela_single_job_submit_general 1046 venezuela_configs/config_venezuela_COA3_buffer_5-sim-1046.json
# bash venezuela_single_job_submit_general 1047 venezuela_configs/config_venezuela_COA3_buffer_5-sim-1047.json
# bash venezuela_single_job_submit_general 1048 venezuela_configs/config_venezuela_COA3_buffer_5-sim-1048.json

#bash venezuela_single_job_submit_general 1050 venezuela_configs/config_venezuela_COA2_COA3_buffer_5-sim-1050.json
#bash venezuela_single_job_submit_general 1051 venezuela_configs/config_venezuela_COA2_COA3_buffer_5-sim-1051.json
#bash venezuela_single_job_submit_general 1052 venezuela_configs/config_venezuela_COA2_COA3_buffer_5-sim-1052.json
#bash venezuela_single_job_submit_general 1053 venezuela_configs/config_venezuela_COA2_COA3_buffer_5-sim-1053.json
#bash venezuela_single_job_submit_general 1054 venezuela_configs/config_venezuela_COA2_COA3_buffer_5-sim-1054.json
#bash venezuela_single_job_submit_general 1055 venezuela_configs/config_venezuela_COA2_COA3_buffer_5-sim-1055.json
#bash venezuela_single_job_submit_general 1056 venezuela_configs/config_venezuela_COA2_COA3_buffer_5-sim-1056.json
#bash venezuela_single_job_submit_general 1057 venezuela_configs/config_venezuela_COA2_COA3_buffer_5-sim-1057.json
#bash venezuela_single_job_submit_general 1058 venezuela_configs/config_venezuela_COA2_COA3_buffer_5-sim-1058.json

bash venezuela_single_job_submit_general 1060 venezuela_configs/config_venezuela_baseline_buffer_5-sim-1060.json
bash venezuela_single_job_submit_general 1061 venezuela_configs/config_venezuela_baseline_buffer_5-sim-1061.json
bash venezuela_single_job_submit_general 1062 venezuela_configs/config_venezuela_baseline_buffer_5-sim-1062.json
bash venezuela_single_job_submit_general 1063 venezuela_configs/config_venezuela_baseline_buffer_5-sim-1063.json
bash venezuela_single_job_submit_general 1064 venezuela_configs/config_venezuela_baseline_buffer_5-sim-1064.json
bash venezuela_single_job_submit_general 1065 venezuela_configs/config_venezuela_baseline_buffer_5-sim-1065.json
bash venezuela_single_job_submit_general 1066 venezuela_configs/config_venezuela_baseline_buffer_5-sim-1066.json
bash venezuela_single_job_submit_general 1067 venezuela_configs/config_venezuela_baseline_buffer_5-sim-1067.json
bash venezuela_single_job_submit_general 1068 venezuela_configs/config_venezuela_baseline_buffer_5-sim-1068.json
